server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api {
        proxy_pass https://backend-le0c.onrender.com;
        proxy_set_header Host backend-le0c.onrender.com;
        proxy_ssl_server_name on;
    }
}
